# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run: mkdir ~/artifacts

      - run: composer install -n --prefer-dist

      - run: ./scripts/circle-deploy.sh

      - store_artifacts:
          path: ~/artifacts
